Repository JackSinnott/JECL_Ducks_Roguelike, pull requests merged in 2022-12, with the labels that each got.

#23 Combat mechanics
  Roguelike/CombatSystem.cpp
  Roguelike/CombatSystem.h
  Roguelike/Enemy.cpp
  Roguelike/Enemy.h
  Roguelike/Game.cpp
  Roguelike/GameOver.cpp
  Roguelike/Gameplay.cpp
  Roguelike/Gameplay.h
  Roguelike/Globals.cpp
  Roguelike/Globals.h
  Roguelike/Help.cpp
  Roguelike/MainMenu.cpp
  Roguelike/Options.cpp
  Roguelike/PauseMenu.cpp
  Roguelike/Player.cpp
  Roguelike/Player.h
  Roguelike/Roguelike.vcxproj
  Roguelike/Roguelike.vcxproj.filters
Labels: enhancement

#24 Dev/collisions
  Roguelike/FileLoader.cpp
  Roguelike/Gameplay.cpp
  Roguelike/Gameplay.h
  Roguelike/Grid.cpp
  Roguelike/Grid.h
  Roguelike/Player.cpp
  Roguelike/Player.h
  Roguelike/Roguelike.vcxproj.filters
  Roguelike/Room.cpp
  Roguelike/Room.h
  Roguelike/Tile.cpp
  Roguelike/Tile.h
Labels: enhancement

#25 Updated some combat doxygen
  Roguelike/CombatSystem.cpp
  Roguelike/CombatSystem.h
  Roguelike/Player.cpp
Labels: documentation, enhancement

#27 Doxygen cleanup of the Abstract items and factories
  Roguelike/AbstractArmour.h
  Roguelike/AbstractItem.h
  Roguelike/AbstractItemFactory.h
  Roguelike/AbstractPotion.h
  Roguelike/AbstractWeapon.h
  Roguelike/ArmourFactory.h
  Roguelike/PotionFactory.h
  Roguelike/WeaponFactory.h
Labels: documentation

#28 Doxygen fix for Screen classes
  Roguelike/AbstractArmour.h
  Roguelike/AbstractItem.h
  Roguelike/AbstractPotion.h
  Roguelike/AxeWeapon.h
  Roguelike/Button.cpp
  Roguelike/Button.h
  Roguelike/DaggerWeapon.h
  Roguelike/Documentation/Doxyfile
  Roguelike/FileLoader.cpp
  Roguelike/FileLoader.h
  Roguelike/Game.cpp
  Roguelike/Game.h
  Roguelike/GameOver.cpp
  Roguelike/GameOver.h
  Roguelike/Gameplay.cpp
  Roguelike/Gameplay.h
  Roguelike/Globals.h
  Roguelike/HealthPotion.h
  Roguelike/HeavyArmour.h
  Roguelike/Help.cpp
  Roguelike/Help.h
  Roguelike/Inventory.cpp
  Roguelike/Inventory.h
  Roguelike/LevelLoader.h
  Roguelike/LightArmour.h
  Roguelike/MainMenu.cpp
  Roguelike/MainMenu.h
  Roguelike/MediumArmour.h
  Roguelike/Options.cpp
  Roguelike/Options.h
  Roguelike/PauseMenu.cpp
  Roguelike/PauseMenu.h
  Roguelike/ResourceAllocator.h
  Roguelike/Room.cpp
  Roguelike/Room.h
  Roguelike/SpeedPotion.h
  Roguelike/StrengthPotion.h
  Roguelike/SwordWeapon.h
  Roguelike/TextureManager.h
  Roguelike/Tile.cpp
  Roguelike/Tile.h
  Roguelike/main.cpp
Labels: documentation

#29 Added class to deal with Audio Objects
  Roguelike/ASSETS/Sounds/Footsteps.wav
  Roguelike/ASSETS/Sounds/Game_Background.ogg
  Roguelike/ASSETS/Sounds/Menu_Theme.ogg
  Roguelike/AbstractItem.h
  Roguelike/AbstractItemFactory.h
  Roguelike/AudioAsset.cpp
  Roguelike/AudioAsset.h
  Roguelike/AudioManager.h
  Roguelike/Game.cpp
  Roguelike/Game.h
  Roguelike/Roguelike.vcxproj
  Roguelike/Roguelike.vcxproj.filters
  Roguelike/TextureManager.h
Labels: enhancement

#30 Up-to-date doxygen
  Roguelike/CombatSystem.cpp
  Roguelike/CombatSystem.h
  Roguelike/Enemy.cpp
  Roguelike/Enemy.h
  Roguelike/Gameplay.cpp
  Roguelike/Grid.cpp
  Roguelike/Grid.h
  Roguelike/Player.cpp
  Roguelike/Player.h
  Roguelike/Room.cpp
  Roguelike/Room.h
Labels: documentation
